### ISSUE TITLE
Status of Windows support

### ISSUE THREAD

**Issue by daemontus** [thepowersgang/va_list-rs#5]
Hi! What is the status of windows support of this library? I need it as a dependency for Z3, but it currently can't be compiled on windows.

However, I see there is some windows related code in there.

So what is the problem? I would be glad to help fixing it, but it would be great to know why that code is commented out :)

**Comment by thepowersgang** [comment]
I didn't end up implementing any form of windows support. If you want to, feel free :) (or I'll attack it if I get time today)

**Comment by thepowersgang** [comment]
I've added a minimally-tested Win64 implementation. Turns out to be a lot simpler than AMD64 :)

**Comment by daemontus** [comment]
Amazing! Thank you very much.
